### ISSUE TITLE
the sparsed model is  much larger than the purned model ,why?

### ISSUE THREAD

**Issue by wang7393** [garion9013/impl-pruning-TF#11]
I done it on my own model and datasets,  the results is:

 ** the first   threshold:**

wd3 threshold:  0.1
Non-zero count (wd3): 9447
wd2 threshold:  0.1
Non-zero count (wd2): 965184
wd1 threshold:  0.1
Non-zero count (wd1): 3861108
Second-round prune-only test accuracy 0.7858

step 0, training accuracy 0.68
step 100, training accuracy 0.8
step 200, training accuracy 0.82
Second-round final test accuracy 0.7366

Non-zero count (Sparse wd3): 10193
Non-zero count (Sparse wd2): 1044382
Non-zero count (Sparse wd1): 4177566

**the second threshold**
wd3 threshold:  0.5
Non-zero count (wd3): 6259
wd2 threshold:  0.5
Non-zero count (wd2): 646845
wd1 threshold:  0.5
Non-zero count (wd1): 2589204
Second-round prune-only test accuracy 0.7858

step 0, training accuracy 0.84
step 100, training accuracy 0.82
step 200, training accuracy 0.8
Second-round final test accuracy 0.7858

Non-zero count (Sparse wd3): 10193
Non-zero count (Sparse wd2): 1044389
Non-zero count (Sparse wd1): 4177563

the question is:
with the different threshold, why the Non-zero count and the size of the model is same ?
and the size of the sparsed model is  much larger than the purned model ,why?

**Comment by younghwanoh** [comment]
1. The result seems weird as you said. It seems that the threshold is applied correctly according to your non-zero value counts, but test accuracy isn't. (It's exactly same in both cases.) Why don't you check whether the test model -- which is pruned -- is correctly assigned while "Second-round prune-only test" or not?

2. Actually it can be bigger than dense model. If threshold isn't big enough, the size of the sparse model is bigger than dense model. You can see the result in my [MNIST experiments.](https://github.com/garion9013/impl-pruning-TF/blob/master/README.md)

### Storage overhead
Baseline(**Dense MNIST model**): 12.49 MB
10 % pruned: 21.86 MB
20 % pruned: 19.45 MB
30 % pruned: 17.05 MB
40 % pruned: 14.64 MB
50 % pruned: 12.23 MB  **(Now sparse model is better compressed than dense model !)**
60 % pruned: 9.83 MB
70 % pruned: 7.42 MB
80 % pruned: 5.02 MB
90 % pruned: 2.61 MB

This is because the sparse matrix form needs "additional data" for matrix indexing.
Thus, to achieve better performance and storage efficiency, the **high sparsity** on your specific network is mandatory. So, try to prune more aggressively with higher thresholds
FYI, TensorFlow uses to <index, data> pair to represent sparse matrix, a.k.a COO.
And COO isn't that so storage efficient form than other sparse matrix format (e.g. CSR).
If you don't like this, try to use [scipy.sparse](https://docs.scipy.org/doc/scipy/reference/sparse.html) module in python.
