### ISSUE TITLE
How to save graph without pruned weights?

### ISSUE THREAD

**Issue by cacfd3a** [garion9013/impl-pruning-TF#13]
I'm following along with your sample code, and it works really well. Except now I am unsure how to freeze my graph for inference. I perform the following code to save:

```py
    # Save model objects to serialized format
    final_saver = tf.train.Saver(sparse_w)
    final_saver.save(sess, "model_ckpt_sparse_retrained")

    # Save graph
    tf.train.write_graph(sess.graph_def, '.', "my_graph.pb", as_text=False)
```

We need the graph file for the freeze code:

```py
from tensorflow.python.tools import freeze_graph, optimize_for_inference_lib
import tensorflow as tf

freeze_graph.freeze_graph(input_graph="my_graph.pb",
                              input_saver="",
                              input_binary=True,
                              input_checkpoint="model_ckpt_sparse_retrained",
                              output_node_names="y_",
                              restore_op_name="save/restore_all",
                              filename_tensor_name="save/Const:0",
                              output_graph="frozen_graph.pb",
                              clear_devices=True,
                              initializer_nodes="")
```

It works on the dense model, but for the sparse model I get an error: `Attempting to use uninitialized value Variable_2`. I suppose this is expected and comes from weights that aren't set in the imported model. Yet they still exist in the graph.

So I suppose we need a way to construct a new graph (since we can delete nodes?). Do you know how to do this? Could we use `graph_util.extract_sub_graph`? Thanks!

**Comment by younghwanoh** [comment]
Hi,

I think you tried to use TF's native API for model saving & restoring.
Unfortunately, this kinds of "normal" workflow of saving & restoring model is not possible in our case.

Because TF doesn't support API for **SparseVariable**.

As you can see in deploy_test_pruned.py, I "manually" construct a graph which is quite different from the graph used in training time. This was my best to use SparseTensor for deployment.
Also, in a same manner, TF doesn't support computation of convolution using SparseTensor.
Thus, my work is just limited to FC layers.
