### ISSUE TITLE
The dense_w  problem

### ISSUE THREAD

**Issue by zhongshaoyy** [garion9013/impl-pruning-TF#8]
I find that the dense_w is a dict in your source code . Does it update during the pruning process? especially in the second-round .After all ,we need to prune the trained weight ,not the original one.

**Comment by younghwanoh** [comment]
Yes, it was bit ambiguous description for usage.
I've intended to use the python script -- [train.py](https://github.com/garion9013/impl-pruning-TF/blob/master/train.py) -- as below

```
// First round
./train.py -1 --> pops "model_ckpt_dense"

// Second round (Prune & retrain the model as you need)
./train.py -2 -m ./model_ckpt_dense
./train.py -2 -m ./model_ckpt_dense_pruned
./train.py -2 -m ./model_ckpt_dense_pruned
./train.py -2 -m ./model_ckpt_dense_pruned

...

// Third round
./train.py -3 --> pops "model_skpt_sparse_retrained"
```


** Also, as [line 185 @ train.py](https://github.com/garion9013/impl-pruning-TF/blob/master/train.py#L185)
saver.restore(sess, args.checkpoint)

The instruction restores weights and overwrites its value to each weight variables that dense_w holds and then you can keep going on for pruning

Anyway, this repository has somewhat unpolished implementation for iterative pruning, and it often misleads and confuses people. But, I truly don't have time to update this repository further now, (e.g. version update, etc.) due to other deadlines. So if you could send some ideas or pull requests to refine this codes, I'll happily accept it.
